local_costmap:
  ros__parameters:
    use_sim_time: true
    global_frame: odom
    robot_base_frame: base_link
    update_frequency: 5.0
    publish_frequency: 2.0
    rolling_window: true
    width: 3.0
    height: 3.0
    resolution: 0.05
    transform_tolerance: 0.5
    plugins: ["obstacle_layer", "inflation_layer"]
 
	
    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      enabled: true
      observation_sources: scan
      robot_radius: 0.22
    scan:
      topic: scan
      data_type: "LaserScan"
      sensor_frame: base_scan
      observation_persistence: 0.0
      expected_update_rate: 0.0
      max_obstacle_height: 2.0
      min_obstacle_height: 0.0
      obstacle_range: 2.5
      raytrace_range: 3.0
      clearing: true
      marking: true
      raytrace_max_range: 3.0
      raytrace_min_range: 0.1
      obstacle_max_range: 2.5
      obstacle_min_range: 0.2
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      enabled: true
      inflation_radius: 0.5
      cost_scaling_factor: 4.0

